version: '3.3'

services:
  app:
    image: ${IMAGE:-eic-customers:latest}
    links:
      - mongo
    environment:
      - MONGO_ENABLED=true
      - MONGO_SERVICE_URI=mongodb://mongo:27017/customers
      - MONGO_COLLECTION=customers
    ports:
      - "8080:8080"

  mongo:
    image: mongo:latest
